<#
.SYNOPSIS
  breakout - open a fresh CLI chat (claude or codex) in a new, self-deleting Warp
  tab on Windows, optionally seeded with a starting prompt. Owns the PowerShell
  seed-escaping that the model-driven inline path keeps getting wrong.

.DESCRIPTION
  The breakout skill calls this on the Windows / PowerShell path. It bakes the
  seed into the new tab's launch command as a single-quoted PowerShell literal
  with embedded double quotes escaped per CommandLineToArgvW - because PowerShell
  5.1 does NOT escape interior " when invoking a native exe, so a bare seed splits
  at the first " and the prompt silently truncates. That truncation is the exact
  bug this script exists to kill; keeping the escaping in code (not inline prose)
  is why it cannot regress.

  The seed reaches this script through a FILE, never a command line - pass
  -SeedFile, not the text - so quotes / newlines / $ / backticks in the prompt
  survive regardless of the caller's shell. The script reads it, bakes the
  escaped literal into the tab config, then deletes the seed file (the launched
  tab runs the baked literal and never re-reads the file).

.EXAMPLE
  breakout.ps1 -LaunchCmd claude -LaunchArgs '--chrome --dangerously-skip-permissions' -SeedFile C:\tmp\seed.txt
.EXAMPLE
  breakout.ps1 -LaunchCmd codex -LaunchArgs '--yolo'   # empty fresh chat, no seed
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$LaunchCmd,                                          # claude | codex
    [string]$LaunchArgs = "",                                                          # e.g. '--chrome --dangerously-skip-permissions'
    [string]$SeedFile = "",                                                            # path to a file holding the seed (robust; never transits a command line)
    [string]$TabConfigsDir = (Join-Path $env:APPDATA "warp\Warp\data\tab_configs")
)
$ErrorActionPreference = "Stop"

# --- Build the launch command, baking in the seed (if any). The seed becomes a
# single-quoted PowerShell literal so $, backticks, and backslashes survive
# verbatim (interior ' are doubled). Interior " are escaped per CommandLineToArgvW
# (double any run of \ before a ", add one more) so the whole prompt reaches the
# native exe as ONE argument under PowerShell 5.1 instead of splitting at the ".
$launch = $LaunchCmd
if ($LaunchArgs) { $launch += " $LaunchArgs" }
if ($SeedFile) {
    if (-not (Test-Path -LiteralPath $SeedFile)) { throw "breakout: -SeedFile not found: $SeedFile" }
    $seed = [System.IO.File]::ReadAllText($SeedFile)
    $seed = ($seed -replace "[\r\n]+", " ").Trim()
    $seed = $seed -replace '(\\*)"', '$1$1\"'
    $launch += " '" + ($seed -replace "'", "''") + "'"
}

# --- Compose the tab command: delete this config first (Warp has already read it,
# so it is race-free and leaves no lingering 'breakout' entry in the + menu), then
# run the CLI with the baked seed.
if (-not (Test-Path $TabConfigsDir)) { New-Item -ItemType Directory -Path $TabConfigsDir -Force | Out-Null }
$cfgPath = Join-Path $TabConfigsDir "breakout.toml"
$qCfg    = "'" + ($cfgPath -replace "'", "''") + "'"
$tabCmd  = "Remove-Item -LiteralPath $qCfg -ErrorAction SilentlyContinue; $launch"

# --- Embed in a TOML basic string: escape backslashes first, then double quotes.
$tabCmdToml = ($tabCmd -replace '\\', '\\') -replace '"', '\"'
$toml = @"
# Warp tab config - generated by the breakout skill (self-deleting; overwritten each run).
name = "breakout"

[[panes]]
id = "main"
type = "terminal"
commands = ["$tabCmdToml"]
"@
# Write UTF-8 without BOM - Warp's TOML parser chokes on a BOM.
[System.IO.File]::WriteAllText($cfgPath, $toml, (New-Object System.Text.UTF8Encoding($false)))

# --- The seed is now baked into the config; the temp file is no longer needed.
if ($SeedFile -and (Test-Path -LiteralPath $SeedFile)) { Remove-Item -LiteralPath $SeedFile -ErrorAction SilentlyContinue }

Start-Process "warp://tab_config/breakout"
Write-Output "breakout: opened a new Warp tab -> $launch"
